import type { Metadata } from 'next'
import SideNav from '@/app/ui/sidenav'
import { Nunito_Sans } from 'next/font/google'
import 'primereact/resources/themes/lara-light-indigo/theme.css'
import 'primeicons/primeicons.css'
import './globals.css'

const nunito = Nunito_Sans({ subsets: ['latin-ext'], weight: '400' })

export const metadata: Metadata = {
  title: 'Buğra Yüksel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
